name               = "mirrors"
main               = "src/index.ts"
compatibility_date = "2024-07-25"

# For local development, use `wrangler dev` to start a local server
[dev]
ip             = "0.0.0.0"
port           = 8787
local_protocol = "http"

[vars]
VERSION = "2.0.0"
SERVICE_NAME = "cf-worker-mirrors"
DOMAINS = ["loopback.mov.pub", "localwin.lan"]
FORBID_HTML = true
